name: 🐞 Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: 버그의 상세한 내용을 설명해주세요.
      placeholder: Bug Description
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      description: 버그 reproduction 방법을 설명해주세요. 사진과 동영상을 첨부하거나, 해당 상황이 구현된 링크 등을 남기면 더 좋습니다!
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Logs
      description: (선택) 버그와 함께 생긴 log를 남겨주세요. 가능한 이미지 대신 텍스트 형식으로 남겨주세요.