name: 🚀 New Feature
description: Propose a new feature to be added to GrabTable
title: "[Feature]: "
body:
  - type: textarea
    attributes:
      label: Describe the feature
      description: 만들고자 하는 feature에 대해 설명해주세요.
    validations:
      required: true