name: 📕 [Frontend] New page development
description: 새로운 page를 개발합니다
title: "[Feature] page-name 페이지 구현
labels: ["feat: frontend"]
body:
  - type: textarea
    attributes:
      label: 🎨 Page Image
      description: 구현하려는 Page의 Image를 첨부해주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✏️ Describe the feature
      description: 구현하려는 page를 자세하게 설명해주세요.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 🏷 Required Component
      description: 해당 page를 구현할 때 필요한 다른 component list를 작성하고, 관련된 issue number를 적어주세요. 없다면 작성하지 않으셔도 됩니다.
    validations:
      required: false
