version: '3'

services:
  app:
    container_name: dev-container-cj
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    depends_on:
      - database
    stdin_open: true
    tty: true

  database:
    container_name: mysql-cj
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: benefit
      MYSQL_ROOT_PASSWORD: root